const {chromium}=require('playwright'),fs=require('fs'),z=require('zlib');
(async()=>{fs.writeFileSync('/tmp/ezp-browser-final',z.brotliDecompressSync(fs.readFileSync('node_modules/@sparticuz/chromium/bin/chromium.br')));fs.chmodSync('/tmp/ezp-browser-final',0o755);const b=await chromium.launch({headless:true,executablePath:'/tmp/ezp-browser-final',args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--no-zygote']});let p=await b.newPage({viewport:{width:1365,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('file:///workspace/scratch/cd4eb899de84/output/Abyssal_Dawn_Earth_Zero_Protocol_v0_1.html');await p.waitForTimeout(500);await p.screenshot({path:'output/title.png'});await p.evaluate(()=>{GW.MainMenu.selectedSlot=1;GW.MainMenu.beginNewGame('character1');GW.MainMenu.finishIntro(true)});await p.waitForTimeout(3000);
let results=await p.evaluate(()=>{const G=GW,S=G.State,E=G.EZP;let results=[];const check=(name,pass,detail='')=>results.push({name,pass:!!pass,detail});const tick=n=>{for(let i=0;i<n*30;i++)G.SceneManager.update(1/30)};S.paused=false;
let metal=S.resources.metal;E.action('build','generator');let u=S.units.find(u=>u.droneRole==='Construction');let x=Math.floor(u.x/48)+2,y=Math.floor(u.y/48)+2;G.Build.previewAt(x*48,y*48);let queued=G.Build.queueCurrent();tick(18);check('Construction travels and completes field generator',queued&&S.buildings.some(b=>b.type==='generator'));check('Construction charges metal',S.resources.metal===metal-100);
E.action('survey');tick(20);check('Survey movement and discovery collect Element P',E.state.elementP>0);let r=E.state.readiness,v=E.state.elementP;E.action('boost');check('Element P consumed to accelerate readiness',E.state.elementP===v-1&&E.state.readiness===Math.max(0,r-90));
let save=G.Save.makeData(),raw=JSON.stringify(save),valid=false;try{E.validate(save);valid=true}catch(err){check('Save validates',false,err.message)}if(valid)check('Save validates',true);check('Save succeeds',G.Save.save(1));let roleIds=S.units.filter(u=>u.droneRole).map(u=>u.id).join();check('Load succeeds',G.Save.load(1));check('Save restores drone IDs',S.units.filter(u=>u.droneRole).map(u=>u.id).join()===roleIds);let bad=JSON.parse(raw);bad.expedition.queue=[{role:'invalid',left:1}];let prior=JSON.stringify(G.Save.makeData().expedition),rejected=false;try{E.restore(bad,1)}catch{rejected=true}check('Malformed import rejected without mutation',rejected&&JSON.stringify(G.Save.makeData().expedition)===prior);
let timer=E.state.readiness;S.paused=true;tick(3);check('Pause freezes expedition timer',E.state.readiness===timer);S.paused=false;
E.state.elapsed=109.99;tick(.1);check('Hostile wave spawns',S.units.some(u=>u.team==='red'));let guard=S.units.find(u=>u.droneRole==='Security'),foe=S.units.find(u=>u.team==='red');foe.x=guard.x+70;foe.y=guard.y;let hp=guard.hp;tick(3);check('Combat resolves damage',guard.hp<hp||foe.hp<65);
S.resources.metal=400;E.action('repair');E.action('recall');tick(20);E.state.readiness=0;let hero=G.getHero(),sh=S.units.find(u=>u.isShip),beforeWorld=E.state.world;let hx=hero.x;hero.x=sh.x+1000;check('Transit rejects absent Vance',E.transit()===false&&E.state.world===beforeWorld);hero.x=hx;
// Place all expedition actors at safe ramp fixture to isolate state transfer from pathfinding.
S.units.filter(u=>u.team==='blue'&&!u.isShip).forEach((u,i)=>{u.x=sh.x-180+i*60;u.y=sh.y+300;u.path=[]});let ids=S.units.filter(u=>u.team==='blue').map(u=>u.id),seed=S.seed;check('Transit succeeds',E.transit());check('New seeded Earth and same crew IDs',S.seed!==seed&&E.state.world===beforeWorld+1&&ids.every(id=>S.units.some(u=>u.id===id)));check('Field buildings left behind, bulk capped',S.buildings.length===0&&S.resources.metal<=300);check('Post-transit save validates',!!E.validate(G.Save.makeData()));
return results;});
await p.waitForTimeout(400);await p.screenshot({path:'output/desktop.png'});await p.click('#ezToggle');await p.screenshot({path:'output/expedition.png'});await p.setViewportSize({width:390,height:844});await p.screenshot({path:'output/mobile.png'});results.push({name:'No browser runtime errors',pass:errors.length===0,detail:errors});fs.writeFileSync('output/verification.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));await b.close();if(results.some(x=>!x.pass))process.exitCode=1})();
