const ROOT=require('path').resolve(__dirname,'..');process.chdir(ROOT);
const fs=require('fs'),path=require('path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,headless:true,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--no-zygote']});
const p=await b.newPage({viewport:{width:1440,height:900}}),errors=[],checks=[];
p.on('pageerror',e=>errors.push(e.message));
await p.addInitScript(()=>{window.requestAnimationFrame=()=>0});
await p.goto('file://'+path.resolve('output/Abyssal_Dawn_Earth_Zero_Protocol_v0_5.html'));
const check=(name,pass,detail)=>{checks.push({name,pass:!!pass,detail});console.log(pass?'PASS':'FAIL',name,pass?'':JSON.stringify(detail??''))};
const tick=async n=>p.evaluate(n=>{for(let i=0;i<n*30;i++)GW.SceneManager.update(1/30);GW.SceneManager.render(performance.now()+3000);},n);
const info=()=>p.evaluate(()=>({world:GW.EZP.state.world,progress:GW.EZP.state.progress,metal:GW.State.resources.metal,ready:GW.EZP.state.readiness,depart:GW.EZP.departure(),scene:GW.SceneManager.currentName,units:GW.State.units.map(u=>({role:u.droneRole||u.type,hp:u.hp,x:u.x,y:u.y,command:u.command,path:u.path.length,cargo:u.resourceCargo}))}));
await p.click('[data-home="new"]');await p.click('[data-new-slot="1"]');await p.fill('#ezSeedInput','72491');await p.click('#launchVance');await p.click('#introSkipBtn');await p.waitForTimeout(100);await tick(5);
check('New game through menu launches Vance, two specialist drones and one Utility Spider',(await info()).units.length===5);
await p.screenshot({path:'evidence/desktop-start.png'});
await p.click('#ezToggle');await p.locator('#ezPanel [data-ez="explore"]').click();await tick(15);
check('Vance physically explores a signal',await p.evaluate(()=>GW.EZP.state.scans>0),await info());
await p.locator('#ezPanel [data-ez="mine"]').click();await tick(45);
check('Utility Spider physically mines, returns and unloads',(await info()).progress.delivered>0,await info());
await p.click('#ezToggle');await p.evaluate(()=>{let u=GW.State.units.find(u=>u.droneRole==='Utility');GW.State.selected=new Set([u.id]);GW.UI.refreshSelection()});await p.click('#truckBuildBtn');await p.evaluate(()=>GW.Build.choose('generator'));
let point=await p.evaluate(()=>GW.screenFromWorld(12288+264,12288+456));
await p.mouse.click(point.x,point.y);await tick(18);
check('Field generator built with the same Utility Spider',(await info()).progress.built===1,await info());
await p.click('#ezToggle');await p.locator('#ezPanel [data-ez="repair"]').click();await tick(1);
check('Drive repaired through expedition log',await p.evaluate(()=>GW.EZP.state.repairs===100));
await tick(100);
check('Live hostile encounter and timer complete',await p.evaluate(()=>GW.EZP.state.waveAt>110)&&(await info()).ready===0&&(await info()).scene==='gameplay',await info());
check('Hostile encounter causes real combat damage',await p.evaluate(()=>GW.State.units.some(u=>u.team==='blue'&&u.hp<u.maxHp)||GW.State.units.filter(u=>u.team==='blue').length<5));
// Mid-expedition persistence: restores all relevant state, with no synthetic resources/positions.
const save=await p.evaluate(()=>GW.Save.makeData());
check('Versioned expedition save validates',await p.evaluate(()=>!!GW.EZP.validate(GW.Save.makeData())));
check('Save/load preserves current expedition',await p.evaluate(()=>{let a=GW.Save.makeData();let ok=GW.Save.save(1)&&GW.Save.load(1);let c=GW.Save.makeData();return ok&&JSON.stringify(a.units)===JSON.stringify(c.units)&&JSON.stringify(a.expedition)===JSON.stringify(c.expedition)&&JSON.stringify(a.inventory)===JSON.stringify(c.inventory)}));
await tick(1);await p.locator('#ezPanel [data-ez="recall"]').click();await tick(25);
check('Recall reaches ship through navigation and unloads all cargo',(await info()).depart.ready,await info());
const before=await p.evaluate(()=>({seed:GW.State.seed,crew:GW.State.units.filter(u=>u.team==='blue').map(u=>({id:u.id,hp:u.hp,maxHp:u.maxHp})),inventory:GW.Save.makeData().inventory,p:GW.EZP.state.elementP,upgrades:GW.EZP.state.upgrades}));
await p.locator('#ezPanel [data-ez="transit"]').click();
let report=await p.evaluate(()=>GW.EZP.state.lastReport);
check('Full expedition completes without teleport/resource/timer fixtures',report?.world===1&&await p.locator('#ezArrival').isVisible(),report);
check('Transit changes seed and retains health, IDs, inventory and Element P',await p.evaluate(before=>GW.State.seed!==before.seed&&before.crew.every(u=>GW.State.units.some(v=>v.id===u.id&&v.hp===u.hp&&v.maxHp===u.maxHp))&&JSON.stringify(GW.Save.makeData().inventory)===JSON.stringify(before.inventory)&&GW.EZP.state.elementP===before.p&&GW.EZP.state.upgrades===before.upgrades,before));
check('Previous Earth structures removed; testing zone regenerated and metal cap applied',await p.evaluate(()=>GW.State.buildings.every(b=>b.testZone)&&GW.State.resources.metal<=300));
await p.screenshot({path:'evidence/arrival.png'});
await p.click('#ezArrivalContinue');await tick(2);
check('Second Earth playable and save/load succeeds',await p.evaluate(()=>GW.EZP.state.world===2&&GW.Save.save(1)&&GW.Save.load(1)));
await p.click('#ezToggle');await tick(1);await p.screenshot({path:'evidence/expedition-panel.png'});
// Keep naturally reached before-transit checkpoint for repeatable rejection fixtures.
fs.writeFileSync('evidence/expedition-checkpoint.json',JSON.stringify(save));
check('No browser runtime errors',errors.length===0,errors);
fs.writeFileSync('evidence/expedition-tests.json',JSON.stringify(checks,null,2));
await b.close();if(checks.some(x=>!x.pass))process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
