const ROOT=require('path').resolve(__dirname,'..');process.chdir(ROOT);
const fs=require('fs'),path=require('path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,headless:true,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--no-zygote']});let p=await b.newPage({viewport:{width:1365,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>window.requestAnimationFrame=()=>0);await p.goto('file://'+path.resolve('output/Abyssal_Dawn_Earth_Zero_Protocol_v0_5.html'));
const results=await p.evaluate(checkpoint=>{
const G=GW,S=G.State,E=G.EZP,out=[];const check=(name,pass,detail)=>out.push({name,pass:!!pass,detail});const tick=n=>{for(let i=0;i<n*30;i++)G.SceneManager.update(1/30)};
E.restore(checkpoint,1);E.action('recall');tick(20);const ready=G.Save.makeData();
const restore=()=>E.restore(JSON.parse(JSON.stringify(ready)),1);
const stable=()=>JSON.stringify({seed:S.seed,world:E.state.world,units:S.units,inventory:G.Save.makeData().inventory,metal:S.resources.metal});
const cases=[['Unrepaired drive',()=>E.state.repairs=0],['Unfinished readiness',()=>E.state.readiness=1],['Absent Vance',()=>G.getHero().x+=3000],['Absent drone',()=>S.units.find(u=>u.droneRole).x+=3000],['Undelivered cargo',()=>S.units.find(u=>u.droneRole==='Utility').resourceCargo.metal=10],['Fabrication queue',()=>E.state.queue.push({role:'Survey',left:2})],['Unfinished construction',()=>S.constructionSites.push({id:'test'})],['Paused game',()=>S.paused=true]];
for(const [name,setup]of cases){restore();setup();let a=stable();check(name+' blocks departure without changing world/cargo/crew',E.transit()===false&&stable()===a)}
restore();let before=E.state.readiness;S.paused=true;tick(3);check('Pause freezes timer',E.state.readiness===before);S.paused=false;
let base=G.Save.makeData();for(const [name,mutate]of [['invalid queue',d=>d.expedition.queue=[{role:'invalid',left:1}]],['negative cargo',d=>d.units.find(u=>u.droneRole==='Utility').resourceCargo.metal=-10],['duplicate ID',d=>d.units[1].id=d.units[0].id],['bad progress',d=>d.expedition.progress.delivered='bad'],['unknown schema',d=>d.schema=999],['negative resources',d=>d.resources.metal=-5]]){let d=JSON.parse(JSON.stringify(base));mutate(d);let a=stable(),rejected=false;try{E.restore(d,1)}catch{rejected=true}check('Import rejects '+name+' without replacing match',rejected&&stable()===a)}
let old=JSON.parse(JSON.stringify(base));delete old.expedition.progress;delete old.expedition.lastReport;try{E.restore(old,1);check('v0.1 schema-1 saves migrate with progress defaults',E.state.progress.delivered===0)}catch(err){check('v0.1 migration',false,err.message)}
restore();let a=stable(),seed=S.seed,Map=G.WorldMap;G.WorldMap=class extends Map{constructor(s){if(s!==seed)throw Error('Injected generation failure');super(s)}};let result=E.transit();G.WorldMap=Map;check('Failed generation rolls back the whole expedition',!result&&stable()===a);
// Seeded terrain and reachable first-expedition critical locations across 12 seed fixtures.
let signatures=[],reachable=true;for(const seed of [72491,72491,1,2,3,44,12345,55555,90817,1345678,2147483647,4294967295]){G.reset({seed});let h=G.getHero(),targets=[...S.scavengeNodes,...E.state.sites.slice(0,3)];reachable=reachable&&targets.every(t=>S.pathfinder.find(h.x,h.y,t.x,t.y,24000).length>0);let hash=2166136261;for(const t of S.map.tiles)hash=Math.imul(hash^t,16777619)>>>0;signatures.push(hash)}
check('Same seed reproduces terrain; different seeds change terrain',signatures[0]===signatures[1]&&signatures[1]!==signatures[2]);check('Initial deposits and first three signals reachable across 12 seed cases',reachable);
G.reset({seed:72491});G.SceneManager.change('gameplay');E.action('build','generator');let u=S.units.find(u=>u.droneRole==='Utility');G.Build.previewAt(u.x+200,u.y+150);let first=G.Build.queueCurrent(),metal=S.resources.metal;E.action('build','sensor');G.Build.previewAt(u.x+250,u.y+150);check('Busy builder rejects a second job without charge',first&&!G.Build.queueCurrent()&&S.resources.metal===metal&&S.constructionSites.length===1);E.action('recall');check('Recall cancels and refunds unfinished construction exactly once',S.constructionSites.length===0&&S.resources.metal===180);E.action('recall');check('Repeated recall cannot duplicate refund',S.resources.metal===180);
G.reset({seed:72491});G.SceneManager.change('gameplay');E.action('build','generator');u=S.units.find(u=>u.droneRole==='Utility');S.map.tiles.fill(2);for(let y=350;y<354;y++)for(let x=350;x<354;x++)S.map.tiles[y*512+x]=0;G.Build.previewAt(351*48,351*48);check('Unreachable build rejected before spending',!G.Build.queueCurrent()&&S.resources.metal===180&&S.constructionSites.length===0);
return out;
},JSON.parse(fs.readFileSync('evidence/expedition-checkpoint.json')));
results.push({name:'No browser runtime errors',pass:errors.length===0,detail:errors});fs.writeFileSync('evidence/guard-tests.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));await b.close();if(results.some(x=>!x.pass))process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
