const ROOT=require('path').resolve(__dirname,'..');process.chdir(ROOT);
const fs=require('fs'),path=require('path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{let b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--no-zygote'],headless:true});let ctx=await b.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true,deviceScaleFactor:1}),p=await ctx.newPage(),errors=[],out=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>window.requestAnimationFrame=()=>0);await p.goto('file://'+path.resolve('output/Abyssal_Dawn_Earth_Zero_Protocol_v0_5.html'));const check=(name,pass)=>out.push({name,pass:!!pass});
await p.locator('[data-home="new"]').tap();await p.locator('[data-new-slot="1"]').tap();await p.locator('#launchVance').tap();await p.locator('#introSkipBtn').tap();await p.waitForTimeout(100);await p.evaluate(()=>{for(let i=0;i<150;i++)GW.SceneManager.update(1/30);GW.SceneManager.render(performance.now()+3000)});
await p.evaluate(()=>GW.EZP.action('focus','hero'));
check('Touch focus-Vance button selects and centers Vance',await p.evaluate(()=>GW.State.selected.has(GW.State.heroId)&&Math.abs(GW.screenFromWorld(GW.getHero().x,GW.getHero().y).x-innerWidth/2)<1));
await p.evaluate(()=>GW.SceneManager.render(performance.now()+3000));await p.screenshot({path:'evidence/mobile-portrait.png'});
const cdp=await ctx.newCDPSession(p);let before=await p.evaluate(()=>({path:JSON.stringify(GW.getHero().path),cam:{...GW.State.camera}}));
await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:360,y:320,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:325,y:365,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
check('Touch pan moves camera without issuing movement',await p.evaluate(v=>GW.State.camera.x!==v.cam.x&&JSON.stringify(GW.getHero().path)===v.path,before));
before=await p.evaluate(()=>({path:JSON.stringify(GW.getHero().path),z:GW.State.camera.z}));
await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:265,y:380,id:1},{x:365,y:480,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:235,y:350,id:1},{x:385,y:510,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
check('Pinch changes zoom without issuing movement',await p.evaluate(v=>GW.State.camera.z>v.z&&JSON.stringify(GW.getHero().path)===v.path,before));
await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:355,y:370,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await p.waitForTimeout(350);
check('Touch cancellation clears pending gestures',await p.evaluate(()=>GW.Input.ptr.size===0&&!GW.Input.touchHold&&!GW.Input.buildGesture&&!GW.Input.pinch));
await p.locator('#ezToggle').tap();await p.screenshot({path:'evidence/mobile-panel.png'});
check('Expedition panel fits portrait viewport',await p.locator('#ezPanel').evaluate(e=>{let r=e.getBoundingClientRect();return r.x>=0&&r.right<=innerWidth&&r.bottom<=innerHeight}));
check('Primary touch controls are at least 44px high',await p.locator('#ezPanel button').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().height>=44)));
await p.locator('#ezToggle').tap();const center=await p.evaluate(()=>({x:GW.State.camera.x+GW.Renderer.w/GW.State.camera.z/2,y:GW.State.camera.y+GW.Renderer.h/GW.State.camera.z/2}));await p.setViewportSize({width:844,height:390});await p.waitForTimeout(100);check('Rotation preserves world center',await p.evaluate(c=>Math.abs(c.x-GW.State.camera.x-GW.Renderer.w/GW.State.camera.z/2)<1&&Math.abs(c.y-GW.State.camera.y-GW.Renderer.h/GW.State.camera.z/2)<1,center));await p.evaluate(()=>GW.SceneManager.render(performance.now()+3000));await p.screenshot({path:'evidence/mobile-landscape.png'});
check('No runtime errors in mobile emulation',errors.length===0);fs.writeFileSync('evidence/mobile-tests.json',JSON.stringify(out,null,2));console.log(out);await b.close();if(out.some(x=>!x.pass))process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
