const ROOT=require('path').resolve(__dirname,'..');process.chdir(ROOT);
const fs=require('fs'),path=require('path');const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,headless:true,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--no-zygote']});const p=await b.newPage({viewport:{width:1365,height:900}}),errors=[],out=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>window.requestAnimationFrame=()=>0);await p.goto('file://'+path.resolve('output/Abyssal_Dawn_Earth_Zero_Protocol_v0_5.html'));
const check=(name,pass)=>{out.push({name,pass:!!pass});console.log(pass?'PASS':'FAIL',name)};
await p.click('[data-home="new"]');await p.click('[data-new-slot="1"]');await p.click('#launchVance');await p.click('#introSkipBtn');await p.waitForTimeout(100);
const tick=async n=>p.evaluate(n=>{for(let i=0;i<n*30;i++)GW.SceneManager.update(1/30);GW.SceneManager.render(performance.now()+3000)},n);await tick(5);
check('New game has exactly one combined Utility Spider',await p.evaluate(()=>GW.State.units.filter(u=>u.droneRole==='Utility').length===1&&!GW.State.units.some(u=>['Mining','Cargo','Construction'].includes(u.droneRole))));
check('Earth information removed from battlefield HUD',await p.locator('#ezHUD').count()===0);
check('Expedition toggle is small and top center',await p.locator('#ezToggle').evaluate(e=>{let r=e.getBoundingClientRect();return Math.abs(r.x+r.width/2-innerWidth/2)<1&&r.y<60&&r.height<=34}));
await p.click('#ezToggle');check('Earth and climate are inside the Expedition log',await p.locator('#ezPanel .ezEarthDetails').innerText().then(t=>t.includes('EARTH 001')&&t.includes('Temperate ruins')));check('Log is compact and centered',await p.locator('#ezPanel').evaluate(e=>{let r=e.getBoundingClientRect();return r.width<=370&&Math.abs(r.x+r.width/2-innerWidth/2)<1&&r.y<90}));await p.screenshot({path:'evidence/v03-log.png'});await p.click('#ezToggle');
await p.evaluate(()=>GW.EZP.action('mine'));let mining=await p.evaluate(()=>{let u=GW.State.units.find(u=>u.droneRole==='Utility');for(let i=0;i<1800&&!GW.UnitVisuals.laserTarget(u);i++)GW.SceneManager.update(1/30);return {id:u.id,laser:GW.UnitVisuals.laserTarget(u)?.mode,cargo:u.resourceCargo.metal,remaining:GW.State.scavengeNodes[0].remaining}});check('Same Utility Spider mines with active laser and finite deposit',mining.laser==='mine'&&mining.cargo>0&&mining.remaining<1200);
await p.evaluate(()=>{let u=GW.State.units.find(u=>u.droneRole==='Utility'),c=GW.State.camera;c.z=1.8;c.x=u.x-GW.Renderer.w/c.z/2;c.y=u.y-GW.Renderer.h/c.z/2;GW.Renderer.draw()});await p.screenshot({path:'evidence/v03-mining.png'});
check('Laser stops when a movement order interrupts mining',await p.evaluate(()=>{let u=GW.State.units.find(u=>u.droneRole==='Utility'),cargo=u.resourceCargo.metal;GW.issueMove([u],u.x+30,u.y+20);return !GW.UnitVisuals.laserTarget(u)&&u.resourceCargo.metal===cargo}));
await p.evaluate(()=>GW.EZP.action('mine'));await tick(45);check('Combined unit carries and delivers metal',await p.evaluate(()=>GW.EZP.state.progress.delivered>0));
let building=await p.evaluate(()=>{const G=GW,S=G.State,u=S.units.find(u=>u.droneRole==='Utility');G.EZP.action('build','generator');G.Build.previewAt(12288+264,12288+456);let queued=G.Build.queueCurrent();for(let i=0;i<1800&&!G.UnitVisuals.laserTarget(u);i++)G.SceneManager.update(1/30);return {id:u.id,queued,laser:G.UnitVisuals.laserTarget(u)?.mode}});check('Same unit switches to construction and uses building laser',building.queued&&building.id===mining.id&&building.laser==='build');
await p.evaluate(()=>{let u=GW.State.units.find(u=>u.droneRole==='Utility'),c=GW.State.camera;c.z=1.8;c.x=u.x-GW.Renderer.w/c.z/2;c.y=u.y-GW.Renderer.h/c.z/2;GW.Renderer.draw()});await p.screenshot({path:'evidence/v03-building.png'});await tick(9);check('Construction completes and its laser stops',await p.evaluate(()=>GW.State.buildings.some(b=>b.type==='generator')&&!GW.UnitVisuals.laserTarget(GW.State.units.find(u=>u.droneRole==='Utility'))));
check('Utility Spider saves and restores as combined role',await p.evaluate(()=>GW.Save.save(1)&&GW.Save.load(1)&&GW.State.units.filter(u=>u.droneRole==='Utility').length===1));
check('Hover engine and spider rendering do not mutate simulation state',await p.evaluate(()=>{let data=JSON.stringify(GW.Save.makeData().units),g=document.createElement('canvas').getContext('2d'),h=GW.getHero(),u=GW.State.units.find(u=>u.droneRole==='Utility');GW.UnitVisuals.hero(g,h,1,10);GW.UnitVisuals.utility(g,u,1,10);return JSON.stringify(GW.Save.makeData().units)===data}));
// Dedicated presentation sheet uses the actual runtime renderers, at two animation times.
await p.evaluate(()=>{let cv=document.createElement('canvas');cv.id='visualCheck';cv.width=720;cv.height=300;cv.style='position:fixed;inset:0;z-index:500;width:720px;height:300px;background:#0e2029';document.body.append(cv);let g=cv.getContext('2d');g.fillStyle='#0e2029';g.fillRect(0,0,720,300);g.fillStyle='#d1e6e8';g.font='16px sans-serif';g.fillText('VANCE / HOVER ENGINE',25,32);g.fillText('UTILITY SPIDER / EIGHT LEGS',370,32);g.save();g.translate(170,240);g.scale(3,3);GW.UnitVisuals.hero(g,GW.getHero(),1,10);g.restore();g.save();g.translate(535,167);g.scale(3,3);GW.UnitVisuals.utility(g,GW.State.units.find(u=>u.droneRole==='Utility'),1,10);g.restore()});await p.locator('#visualCheck').screenshot({path:'evidence/v03-unit-visuals.png'});await p.evaluate(()=>document.getElementById('visualCheck').remove());
// Genuine prior-version save fixture, retains all owned actors and their inventory.
let old=JSON.parse(fs.readFileSync('history/v0_2/checkpoint.json'));check('Old specialist saves convert without losing IDs, health, cargo or inventory',await p.evaluate(old=>{let ids=old.units.map(u=>u.id),expected=old.units.filter(u=>['Construction','Cargo','Mining'].includes(u.droneRole)).length;GW.EZP.restore(old,1);return GW.State.units.filter(u=>u.droneRole==='Utility').length===expected&&ids.every(id=>GW.State.units.some(u=>u.id===id))&&old.units.every(u=>{let v=GW.State.units.find(v=>v.id===u.id);return v.hp===u.hp&&JSON.stringify(v.resourceCargo)===JSON.stringify(u.resourceCargo)})&&JSON.stringify(GW.Save.makeData().inventory)===JSON.stringify(old.inventory)},old));
check('No browser runtime errors',errors.length===0);fs.writeFileSync('evidence/v03-tests.json',JSON.stringify(out,null,2));await b.close();if(out.some(x=>!x.pass))process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
