const ROOT=require('path').resolve(__dirname,'..');process.chdir(ROOT);
const fs=require('fs'),path=require('path'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--no-zygote']}),out=[];
for(const touch of [false,true]){const p=await b.newPage({viewport:touch?{width:390,height:844}:{width:1365,height:900},hasTouch:touch,isMobile:touch}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>window.requestAnimationFrame=()=>0);await p.goto('file://'+path.resolve('output/Abyssal_Dawn_Earth_Zero_Protocol_v0_5.html'));
const check=(name,pass)=>{out.push({name:(touch?'Touch: ':'Desktop: ')+name,pass:!!pass});console.log(pass?'PASS':'FAIL',out.at(-1).name)};
for(const sel of ['[data-home="new"]','[data-new-slot="1"]','#launchVance','#introSkipBtn'])await p.locator(sel)[touch?'tap':'click']();await p.waitForTimeout(100);
await p.evaluate(()=>{for(let i=0;i<150;i++)GW.SceneManager.update(1/30);GW.EZP.action('focus','ship');GW.SceneManager.render(performance.now()+3000)});
check('Objectives system absent',await p.evaluate(()=>!document.querySelector('#ezObjective,#ezObjectiveTab')&&!GW.EZP.objective));
check('Procedural Element P, chests and ground items removed',await p.evaluate(()=>GW.EZP.state.sites.every(s=>s.kind!=='Element P')&&GW.State.map.loot.length===0&&GW.State.map.items.length===0&&GW.State.containers.every(c=>c.testZone)));
check('Generated world buildings removed',await p.evaluate(()=>GW.State.map.buildings.length===0));
check('Every item and building is represented once left of ship',await p.evaluate(()=>{const S=GW.State,sh=S.units.find(u=>u.isShip),items=Object.keys(GW.ItemDefs),buildings=Object.keys(GW.DATA.BUILDABLES);return items.every(k=>S.containers.filter(c=>c.testZone&&c.type==='ground_item'&&c.items[0]?.key===k&&c.x<sh.x).length===1)&&buildings.every(k=>k==='chest'?S.containers.filter(c=>c.testZone&&c.built&&c.x<sh.x).length===1:S.buildings.filter(b=>b.testZone&&b.type===k&&b.x<sh.x).length===1)&&S.buildings.length===buildings.length-1&&S.containers.length===items.length+1}));

const select=async()=>{await p.evaluate(()=>{GW.Input.clearSelection();GW.EZP.action('focus','ship');GW.SceneManager.render(performance.now()+3000)});let q=await p.evaluate(()=>{let s=GW.State.units.find(u=>u.isShip);return GW.screenFromWorld(s.x,s.y)});if(touch)await p.touchscreen.tap(q.x,q.y);else await p.mouse.click(q.x,q.y);await p.locator("#ezFabrication").waitFor({state:"visible"})};
await select();check('Selecting ship opens fabrication immediately',await p.locator('#ezFabrication').isVisible());check('Fabrication stays next to ship',await p.evaluate(()=>{let q=GW.screenFromWorld(GW.State.units.find(u=>u.isShip).x,GW.State.units.find(u=>u.isShip).y),r=document.getElementById('ezFabrication').getBoundingClientRect();return r.width<=265&&r.height<=322&&Math.hypot(r.x+r.width/2-q.x,r.y+r.height/2-q.y)<410}));check('Ship excluded from movement commands',await p.evaluate(()=>GW.State.selected.has(GW.State.shipId)&&GW.Input.selectedUnits().length===0));
check('Available builds and costs displayed',await p.locator('#ezFabBody [data-ez="fabricate"]').count()===3&&await p.locator('#ezFabBody').innerText().then(t=>t.includes('160 metal')&&t.includes('Utility Spider')));
await p.screenshot({path:`evidence/v05-fabrication-${touch?'touch':'desktop'}.png`});let metalBefore=await p.evaluate(()=>GW.State.resources.metal);if(touch){await p.waitForTimeout(100);let r=await p.locator('#ezFabBody [data-arg="Utility"]').boundingBox();await p.touchscreen.tap(r.x+r.width/2,r.y+r.height/2)}else await p.locator('#ezFabBody [data-arg="Utility"]').click();check('Build deducts cost and enters queue',await p.evaluate(before=>GW.State.resources.metal===before-160&&GW.EZP.state.queue.length===1,metalBefore));
check('Affordability reflected in options',await p.evaluate(()=>[...document.querySelectorAll('#ezFabBody [data-ez="fabricate"]')].every(b=>b.disabled===(GW.State.resources.metal<GW.EZP.roles[b.dataset.arg].cost))));
await p.evaluate(()=>{for(let i=0;i<390;i++)GW.SceneManager.update(1/30)});check('Fabrication deploys new Utility Spider',await p.evaluate(()=>GW.EZP.state.queue.length===0&&GW.State.units.filter(u=>u.droneRole==='Utility').length===2));
await p.locator('#ezFabClose')[touch?'tap':'click']();check('Close button dismisses window',!await p.locator('#ezFabrication').isVisible());if(touch)await p.waitForTimeout(350);await select();check('Can reopen by selecting ship',await p.locator('#ezFabrication').isVisible());await p.evaluate(()=>GW.Input.clearSelection());check('Clearing selection closes window',!await p.locator('#ezFabrication').isVisible());
await p.locator('#ezToggle')[touch?'tap':'click']();check('Log excludes fabrication and construction controls',await p.locator('#ezPanel [data-ez="fabricate"],#ezPanel [data-ez="build"]').count()===0&&await p.locator('#ezPanel h3').allTextContents().then(t=>!t.includes('Fabrication')&&!t.includes('Field construction')));
if(touch){await p.locator('#ezToggle').tap();await p.evaluate(()=>{GW.Input.clearSelection();GW.EZP.action('focus','ship')});let before=await p.evaluate(()=>({metal:GW.State.resources.metal,queue:GW.EZP.state.queue.length})),q=await p.evaluate(()=>{let u=GW.State.units.find(u=>u.isShip);return GW.screenFromWorld(u.x,u.y-80)});await p.touchscreen.tap(q.x,q.y);check('Selecting top of ship does not purchase from opening window',await p.evaluate(v=>GW.State.resources.metal===v.metal&&GW.EZP.state.queue.length===v.queue&&GW.State.selected.has(GW.State.shipId),before));}
check('No runtime errors',errors.length===0);await p.close()}
fs.writeFileSync('evidence/v05-tests.json',JSON.stringify(out,null,2));await b.close();if(out.some(c=>!c.pass))process.exitCode=1})().catch(e=>{console.error(e);process.exit(1)});
